Feature/link database section
sdp-sharelook/App pull request #131
Opened 2022-04-28 16:19 UTC by edoulaX

2022-04-28 18:35 UTC, AdrianUlrich approved these changes
Very good

2022-04-28 18:35 UTC, AdrianUlrich commented on app/src/main/java/com/github/sdpsharelook/Section/Section.kt
> +        var section = other as Section
That looks dangerous

2022-04-28 18:35 UTC, AdrianUlrich commented on app/src/main/java/com/github/sdpsharelook/Section/SectionActivity.kt
> +            var newSection = Section(
Maybe Builder Pattern?

2022-04-28 18:35 UTC, AdrianUlrich commented on app/src/main/java/com/github/sdpsharelook/Section/SectionActivity.kt
> +                Toast.makeText(this, "Section: " + sectionName + " edited", Toast.LENGTH_SHORT).show()
Use string template "Section: $sectionName edited"

2022-05-01 18:37 UTC, albastardoto commented on app/src/main/java/com/github/sdpsharelook/Section/Section.kt
>      val id: Int? = sectionList.size
SectionList.size shouldn't be used for ids, rename variable if needed to avoid confusion.

2022-05-19 13:20 UTC, AdrianUlrich requested changes
Some changes controversial
Some are unacceptable
Fix the injection and serialisation

2022-05-19 13:20 UTC, AdrianUlrich commented on app/src/main/java/com/github/sdpsharelook/section/Section.kt
> +    val databaseRepo: RTDBWordListRepository,
No, inject it properly

2022-05-19 13:20 UTC, AdrianUlrich commented on app/src/main/java/com/github/sdpsharelook/section/Section.kt
> +        return sectionRepo == section.sectionRepo
Hello no you don't

2022-05-19 13:20 UTC, AdrianUlrich commented on app/src/main/java/com/github/sdpsharelook/section/Section.kt
> +        return sectionRepo == section.sectionRepo
Repos don't hold state

2022-05-19 13:20 UTC, AdrianUlrich commented on app/src/main/java/com/github/sdpsharelook/storage/RTDBWordListRepository.kt
> +) : IRepository<@JvmSuppressWildcards Word> {
Noooooooooooooooo my tests

Also@JvmSuppressWildcards is no longer necessary here

2022-05-24 19:34 UTC, AdrianUlrich submitted a review, later dismissed
Still has problems

2022-05-24 19:34 UTC, AdrianUlrich commented on app/src/main/java/com/github/sdpsharelook/section/CardAdapter.kt
> +    private val wordRTDB : RTDBWordListRepository
Should still be an interface typed variable
```suggestion
    private val wordRepo: IRepository<List<Word>>
```

2022-05-24 19:34 UTC, AdrianUlrich commented on app/src/main/java/com/github/sdpsharelook/translate/TranslateFragment.kt
> +        Log.e("sdection word", Json.encodeToString(sectionWord).toString())
testing stuff to be removed

2022-05-29 09:02 UTC, rombirli approved these changes

2022-05-29 09:06 UTC, rombirli commented
Please also decrease complexity of app/src/main/java/com/github/sdpsharelook/section/SectionFragment.kt onViewCreated since it has 44lines (25max recommended)

2022-05-29 18:58 UTC, AdrianUlrich requested changes
Ba du coup je dis non pasque j'aime bien quand on reverse pas mes changements sans raison

2022-05-29 18:58 UTC, AdrianUlrich commented on app/build.gradle
> -            // android
This undoes work on the jacoco script done by me...

2022-05-29 19:49 UTC, AdrianUlrich reviewed
Extra comments

2022-05-29 19:49 UTC, AdrianUlrich commented on app/src/main/java/com/github/sdpsharelook/section/SectionDetailFragment.kt
> +class SectionDetailFragment : Fragment() {
Reverses my changes

2022-05-29 19:49 UTC, AdrianUlrich commented on app/src/main/java/com/github/sdpsharelook/section/SectionFragment.kt
> +class SectionFragment : Fragment(), SectionClickListener {
1. Reverses my changes
2. Ugly global state

2022-05-29 19:49 UTC, AdrianUlrich commented on app/src/main/java/com/github/sdpsharelook/section/SectionFragment.kt
> +        // set up the popup when cliking on add button
Reverses my changes

2022-05-29 19:49 UTC, AdrianUlrich commented on app/src/main/java/com/github/sdpsharelook/section/WordAdapter.kt
> +        }
Duplication why?

2022-05-29 20:05 UTC, AdrianUlrich approved these changes
Thanks for the speedy changes

2022-05-30 08:08 UTC, merged